# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly
notifications:
  email: false

matrix:
  allow_failures:
  - julia: nightly

env:
  matrix:
    - JULIA_NUM_THREADS=1
    - JULIA_NUM_THREADS=4
#
## uncomment the following lines to override the default test script

after_success:
  # push coverage results to Codecov and Coveralls
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder()); Coveralls.submit(Coveralls.process_folder())'
